using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using SynUbePatcher.Settings;

namespace SynUbePatcher
{
    public class Program
    {
        static Lazy<PatcherSettings> Settings = null!;              

        public static async Task<int> Main(string[] args)
        {                       
            var excludedModKeys = new List<ModKey>
            {
                ModKey.FromFileName("Skyrim.esm"),
                ModKey.FromFileName("Update.esm"),
                ModKey.FromFileName("Dawnguard.esm"),
                ModKey.FromFileName("Dragonborn.esm"),
                ModKey.FromFileName("Hearthfires.esm"),
                ModKey.FromFileName("UBE_AllRace.esp")
            };

            var preferences = new PatcherPreferences()
            {
                IncludeDisabledMods = false,
                AddImplicitMasters = false,
                NoPatch = false,
                ExclusionMods = excludedModKeys
            };

            var debugArgs = new string[] {
                "run-patcher",
                "--OutputPath", "M:\\Data_test\\",
                "--GameRelease", "SkyrimSE",
                "--DataFolderPath", "M:\\Data_test\\",
                "--LoadOrderFilePath", "M:\\Data_test\\plugins.txt"
            };

            var a = await SynthesisPipeline.Instance
                 .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out Settings)
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch, preferences)                
                .SetTypicalOpen(GameRelease.SkyrimSE, "UBE_SynthesisPatch.esp")              
                //.AddRunnabilityCheck(CheckRunnability)
                .Run(args);            

            return a;
        }       
        
        public static void CheckRunnability(IRunnabilityState state)
        {
            state.LoadOrder.AssertListsMod("UBE_AllRace.esp", "You need UBE_AllRace.esp to be loaded!");            
        }

        string[] kTargetRacesEditorIDs = new string[] 
        { 
            @"00UBE_BretonRace",
            @"00UBE_CustomRace01",
            @"00UBE_CustomRace02"
        };

        string[] kArmorAddonsTemplateEditorIDs = new string[]
       {
            @"UBE_TemplateAA",
            @"UBE_CustomRace01_TemplateAA",
            @"UBE_CustomRace02_TemplateAA"
       };   

        string[] kArmorAddonElementsToNotUpdate = new string[]
        {
            @"Record Header",
            @"EDID - Editor ID",
            @"RNAM - Race",
            @"Additional Races"
        };
     
        static void Print(string message, int step = 0)
        {
            var tabString = "";
            for (int i = 0; i < step; i++)
                tabString += "  ";
            Console.WriteLine($"{tabString}{message}");
        }
              
        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            var settings = Settings.Value;           
            var patcher = new UbePatcher(state, settings);
            patcher.Patch();
        }
    }
}
